# /Users/jonathon/.config/tmuxinator/dev.yml
name: dev
root: ~/

windows:
  - dev:
      root: /code
      layout: even-vertical
      panes:
        - opencode
        - clear && cat /usr/local/share/welcome.txt && bash
