# /Users/jonathon/.config/tmuxinator/dev.yml
name: dev
root: ~/

windows:
  - dev:
      root: /code
      layout: even-vertical
      panes:
        - opencode
        - clear && /usr/local/bin/show-welcome.py && bash
